name: Download built package from cache
description: Download built package from cache
runs:
  using: "composite"
  steps:
  - name: Download built package from cache
    uses: actions/download-artifact@v6
    with:
      name: bulit-assets
      path: table
  - name: 'Install dependencies'
    shell: 'bash'
    run: pnpm install --force
  - name: Show output
    run: |
      ls -la table/dist
      ls -la table/declarations
    shell: bash
