name: Build and Assert Assets Exists
description: Build the package and assert that file contents exist as we expect
runs:
  using: "composite"
  steps:
  - name: Build and Assert Output
    shell: bash
    run: |-
      echo '
        target: table
        setup:
          run: pnpm build
          cwd: ./table
        expect: |
          dist/index.js
          dist/index.js.map
          declarations/index.d.ts
          dist/plugins/index.js
          dist/plugins/data-sorting/index.js
          dist/plugins/column-reordering/index.js
          dist/plugins/column-resizing/index.js
          dist/plugins/column-visibility/index.js
          dist/plugins/sticky-columns/index.js
          dist/test-support/index.js

      ' >> assert-contents.config.yml
      npx assert-folder-contents

  - name: Upload dist assets to cache
    uses: actions/upload-artifact@v5
    with:
      name: bulit-assets
      path: table
